import { Country } from '../providers.js';

export enum Countries {
  UK = 'united-kingdom',
  Germany = 'germany',
  USA = 'united-states',
  France = 'france',
  China = 'china',
  Canada = 'canada',
  Terroruzzia = 'russia',
  Mauritius = 'mauritius',
  Morocco = 'morocco',
  Poland = 'poland',
  Netherlands = 'netherlands',
  India = 'india',
  Israel = 'israel',
  Kazakhstan = 'kazakhstan',
  Mexico = 'mexico',
  Indonesia = 'indonesia',
  Portugal = 'portugal',
  Thailand = 'thailand',
  Philippines = 'philippines',
  Croatia = 'croatia',
  Sweden = 'sweden',
  HongKong = 'hong-kong',
  Finland = 'finland',
  Ukraine = 'ukraine',
  Ireland = 'ireland',
  Nigeria = 'nigeria',
  Brazil = 'brazil',
  Belgium = 'belgium',
  Spain = 'spain',
  Romania = 'romania',
  CzechRepublic = 'czech-republic',
  Italy = 'italy',
  Japan = 'japan',
  Austria = 'austria',
  Australia = 'australia',
  Taiwan = 'taiwan',
  Singapore = 'singapore',
  SouthKorea = 'south-korea'
}

export const countries = Object.keys(Countries) as Country[];
